### ISSUE TITLE
Error downloading the mike/osv-loader image

### ISSUE THREAD

**Issue by techmonte** [mikelangelo-project/capstan#105]
Running into an GZip error with the Capstan tool when attempting to run the `capstan pull mike/osv-loader` command.  GZip reports an "Invalid Header" message.  The image is being pulled from https://mikelangelo-capstan.s3.amazonaws.com/mike/osv-loader/osv-loader.vbox.gz

**Comment by wkozaczuk** [comment]
Hi,

This fork of capstan has not been maintained anymore and has been merged
into main capstan repo - https://github.com/cloudius-systems/capstan
