### ISSUE TITLE
Error when attempting to compose an OSv package.  Get signal: abort trap error

### ISSUE THREAD

**Issue by techmonte** [mikelangelo-project/capstan#106]
Running into an issue with the Capstan tool when attempting to compose a package using the `capstan package compose...` command. Upon executing the command, the composition process begins and after executing the `Setting:cmdline: --norandom --nomount ...` task, the process immediately halts with a `signal: abort trap` error.  I've been unable to locate anything within the tutorial or help documentation that assists in troubleshooting this error.

**Comment by wkozaczuk** [comment]
Hi,

This fork of capstan has not been maintained anymore and has been merged
into main capstan repo - https://github.com/cloudius-systems/capstan
