### ISSUE TITLE
Proposal for configset description of a composed image

### ISSUE THREAD

**Issue by miha-plesko** [mikelangelo-project/capstan#5]
(upgrade of https://github.com/mikelangelo-project/capstan/issues/4)

Capstan should be able to print runtime options of a composed image:

```
$ capstan runtime info mike/my-app
```

This command should print all the available config_set names and details. 

The command should only rely on the information stored inside the image (as opposed to reading meta/run.yaml from the current directory on the host).
### Proposed solution

While composing, Capstan should also store the original meta/run.yaml file into OSv image. Then the `capstan runtime info` command could access this file and print it.

Optionally, Capstan could parse the file and print it in a more sophisticated way.

**Comment by gberginc** [comment]
Would this require the agent mentioned in #4 to be running in the VM? Basically, Capstan would just invoke a command on the agent that would then return information from the given YAML file residing in the VM instance?
