### ISSUE TITLE
Issue with the osv.bootstrap pkg & the repository

### ISSUE THREAD

**Issue by nikoszoisse** [mikelangelo-project/capstan#78]
Hello guys, I was trying to compose a OSv Image using capstan, therefore I faced this issue when i was trying to collect the missing packages

capstan package collect --pull-missing
package eu.mikelangelo-project.osv.bootstrap is not available in the given repository (https://mikelangelo-capstan.s3.amazonaws.com/)

I ve found that you changed the xml, what I have to change in order to make it work? 

Thanks.

**Comment by miha-plesko** [comment]
Hi @nikoszoisse. Problem is that you're using obsolete Capstan binary, and it's NOT your fault, we really need to publish a new release. Best way is that you compile the Capstan master yourself, but here's the shortcut, I've compiled it for you just now:

http://x.k00.fr/capstanpkgs

Also, I've included all the latest packages in this .zip be totally sure that you're fully up-to-date. Please let me know if it works and thanks for your patience.

**Comment by nikoszoisse** [comment]
I ve tried also to build it from sources, but go 1.7.3 gives me too many errors, I will try today your compiled version!

**Comment by nikoszoisse** [comment]
Okay everything now is works!! Thank you. I built capstan with go v1.9 successfully and also capstan binary succeed @ pull missing command!

**Comment by miha-plesko** [comment]
Interesting that it doesnt compile on 1.7.3, because Travis seems to have [no problems](https://travis-ci.org/mikelangelo-project/capstan/builds/298962564?utm_source=github_status&utm_medium=notification). Well, I'm glad you made it 👍
