### ISSUE TITLE
Private repo gzip

### ISSUE THREAD

**Issue by yieldone** [mikelangelo-project/capstan#96]
Hi folks,

I'm trying to make a private repo to store our custom image (merging packages takes too long). I've created my own repo, in which I've made osv-loader.qemu.gz the custom image. Uploading works fine, however, when attempting to pull via Capstan I get: 

`gzip: invalid header`

I'm using commandline gzip to compress the image - is there any incompatibility between Go and gzip?

Cheers,

Rowland

**Comment by miha-plesko** [comment]
Hi @yieldone, no, there shouldn't be any incompatibility issues. In fact, we use `gzip` to prepare our loader image as well, see [here](https://github.com/mikelangelo-project/capstan-packages/blob/master/docker_files/capstan-packages.py#L226-L259).

I think I've seen similar error appear when there was permission issue. Can you please try to `chmod 777 osv-loader.qemu.gz` prior uploading the image to repository?

**Comment by yieldone** [comment]
Many thanks for the suggestion, I've tried chmod 777 but doesn't seem to change things. What about the yaml file - does this need to reflect that actual image file at all?

**Comment by miha-plesko** [comment]
No, yaml file just needs to be present. Did you also try to chmod 777 prior gzipping? Also, please compare your gzip with the current one, maybe you zipped with directory or something :)

**Comment by yieldone** [comment]
Ah ha, it was an S3 permission issue - wasn't public, that solves the download issue, thanks!
