### ISSUE TITLE
Support Read-only FS images

### ISSUE THREAD

**Issue by wkozaczuk** [mikelangelo-project/capstan#98]
As of the commit https://github.com/cloudius-systems/osv/commit/1f122aee15bd294a34990f81fd1133121dde87f5 OSv supports Read-Only File System (ROFS). It would be nice to have capstan support building ROFS images (vs ZFS ones it does now). In essence we would need to replicate what this Python script does - https://github.com/cloudius-systems/osv/blob/master/scripts/gen-rofs-img.py

**Comment by miha-plesko** [comment]
Awesome @wkozaczuk , congratulations on bringing ROFS to life! I want to let you know, however, that we currently have no resources to perform such upgrade of Capstan, so it will have to wait for a PR by someone else...
